# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NomadLogger < Formula
  desc ""
  homepage ""
  version "0.2.1"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/attachmentgenie/nomad-logger/releases/download/v0.2.1/nomad-logger_0.2.1_darwin_arm64.zip"
      sha256 "17ee8a2d5cef9d4631560fab6983df7bbf0df764d7b9bf3bf55b7f8d3ce1a694"

      def install
        bin.install "nomad-logger"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/attachmentgenie/nomad-logger/releases/download/v0.2.1/nomad-logger_0.2.1_darwin_amd64.zip"
      sha256 "41834b8ff371c6fd2fb559d52b2d5ff509f0d3fefff81cb6c1f7d56e5add5527"

      def install
        bin.install "nomad-logger"
      end
    end
  end
end
