# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NomadLogger < Formula
  desc ""
  homepage ""
  version "0.7.0"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/attachmentgenie/nomad-logger/releases/download/v0.7.0/nomad-logger_0.7.0_darwin_arm64.zip"
      sha256 "53edbf50ed7577afe84ada422ce462051cb422f24999826271368b456eaa9aa5"

      def install
        bin.install "nomad-logger"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/attachmentgenie/nomad-logger/releases/download/v0.7.0/nomad-logger_0.7.0_darwin_amd64.zip"
      sha256 "f64d29be71497513f7f6324a6f04b0a3248dc91f8d9f106ed9e4b4779a4ec4f2"

      def install
        bin.install "nomad-logger"
      end
    end
  end
end
